services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    user: 10001:10001
    networks:
      - nginx_ip4_network
    volumes:
      - ./cache:/cache
      - ./config:/config
      - /media:/media:ro

networks:
  nginx_ip4_network:
    external: true
