services:
  jellyfin:
    image: jellyfin/jellyfin:10.9.8
    container_name: jellyfin
    restart: unless-stopped
    networks:
      - nginx_ip4_network
    environment:
      NETWORK_ACCESS: internal
      VIRTUAL_HOST: "streaming.${DOMAIN}"
      VIRTUAL_PORT: 8096
    volumes:
      - ./cache:/cache
      - ./config:/config
      - /media:/media

networks:
  nginx_ip4_network:
    external: true
