- name: Create Outline app container directory
  ansible.builtin.file:
    path: "{{ quadlet_path }}/outline"

- name: Create Outline data directory
  ansible.builtin.file:
    path: "{{ storage }}/outline/data"

- name: Create Outline cache directory
  ansible.builtin.file:
    path: "{{ storage }}/outline/cache"

- name: Create Outline db directory
  ansible.builtin.file:
    path: "{{ storage }}/outline/db"
