- name: Create {{ container_name }} secret key
  containers.podman.podman_secret:
    data: "{{ secret_key }}"
    name: OUTLINE_SECRET_KEY

- name: Create {{ container_name }} client secret
  containers.podman.podman_secret:
    data: "{{ client_secret }}"
    name: OUTLINE_CLIENT_SECRET

- name: Create {{ container_name }} utils secret
  containers.podman.podman_secret:
    data: "{{ utils_secret }}"
    name: OUTLINE_UTILS_SECRET

- name: Create {{ container_name }} DB username
  containers.podman.podman_secret:
    data: "{{ db_username }}"
    name: OUTLINE_DB_USERNAME

- name: Create {{ container_name }} DB password
  containers.podman.podman_secret:
    data: "{{ db_password }}"
    name: OUTLINE_DB_PASSWORD

- name: Create {{ container_name }} database URL
  containers.podman.podman_secret:
    data: "{{ db_url }}"
    name: OUTLINE_DB_URL
