- name: Create Outline secret key
  containers.podman.podman_secret:
    name: OUTLINE_SECRET_KEY
    data: query('community.general.random_string', override_all=hex_chars, length=64)

- name: Create Outline client secret
  containers.podman.podman_secret:
    name: OUTLINE_CLIENT_SECRET
    data: query('community.general.random_string', override_all=hex_chars, length=128)

- name: Create Outline utils secret
  containers.podman.podman_secret:
    name: OUTLINE_UTILS_SECRET
    data: query('community.general.random_string', override_all=hex_chars, length=64)

- name: Create Outline DB username
  containers.podman.podman_secret:
    name: OUTLINE_DB_USERNAME
    data: lookup('community.general.random_string', length=12)

- name: Create Outline DB password
  containers.podman.podman_secret:
    name: OUTLINE_DB_PASSWORD
    data: lookup('community.general.random_string', length=32)
