services:
  nginx:
    image: nginxproxy/nginx-proxy:1.6.0
    container_name: nginx-proxy
    restart: unless-stopped
    networks:
      - nginx_ip4_network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./internal.conf:/etc/nginx/network_internal.conf
      - ./config:/etc/nginx/conf.d
      - certs:/etc/nginx/certs:ro
  acme:
    image: cilenco/lego-cron-wrapper:v4.14.2
    container_name: nginx-certs
    restart: unless-stopped
    networks:
      - nginx_ip4_network
    command: >
      --accept-tos --email=${EMAIL} --dns ionos
      --domains=*.${DOMAIN} --domains=${DOMAIN}
    # --server=https://acme-staging-v02.api.letsencrypt.org/directory
    environment:
      RUN_ARGUMENTS: --run-hook=/app/deploy
      RENEW_ARGUMENTS: --renew-hook=/app/deploy
      IONOS_API_KEY_FILE: /app/credentials
      IONOS_PROPAGATION_TIMEOUT: 120
      IONOS_POLLING_INTERVAL: 20
    volumes:
      - certs:/app/certificates
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./credentials:/app/credentials
      - ./deploy.sh:/app/deploy

networks:
  nginx_ip4_network:
    name: nginx_ip4_network

volumes:
  certs:
    external: true
