services:
  nginx:
    image: nginxinc/nginx-unprivileged
    container_name: nginx-server
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./config:/etc/nginx/conf.d
      - certs:/etc/nginx/certs:ro
    networks:
      - nginx_ip4_network
  dockergen:
    image: nginxproxy/docker-gen:0.14.2
    container_name: nginx-config
    restart: unless-stopped
    command: |
      -notify-sighup nginx-server -watch
      /etc/docker-gen/templates/nginx.tmpl
      /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - nginx_ip4_network
  acme:
    image: nginxproxy/acme-companion:2.5.0
    container_name: nginx-certs
    restart: unless-stopped
    volumes_from:
      - nginx
    volumes:
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme:/etc/acme.sh
    environment:
      NGINX_DOCKER_GEN_CONTAINER: nginx-config
      DEFAULT_EMAIL: noreply@${DOMAIN}
      ACME_CHALLENGE: DNS-01
      ACMESH_DNS_API_CONFIG: |-
        DNS_API: dns_ionos
        IONOS_PREFIX: ${PREFIX}
        IONOS_SECRET: ${SECRET}

networks:
  nginx_ip4_network:
    name: nginx_ip4_network

volumes:
  certs:
    external: true
