services:
  nginx:
    image: nginxproxy/nginx-proxy:1.6.1
    container_name: nginx-proxy
    restart: unless-stopped
    networks:
      - nginx_ip4_network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./internal.conf:/etc/nginx/network_internal.conf
      - ./config:/etc/nginx/conf.d
      - certs:/etc/nginx/certs:ro
  acme:
    image: nginxproxy/acme-companion:2.4.0
    container_name: nginx-certs
    restart: unless-stopped
    networks:
      - nginx_ip4_network
    volumes:
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme.sh:/etc/acme.sh
    environment:
      ACMESH_VERSION: 3.0.8
      DEFAULT_EMAIL: noreply@${DOMAIN}
      ACME_CHALLENGE: DNS-01
      ACMESH_DNS_API_CONFIG: |-
        DNS_API: dns_ionos
        IONOS_PREFIX: ${PREFIX}
        IONOS_SECRET: ${SECRET}

networks:
  nginx_ip4_network:
    name: nginx_ip4_network

volumes:
  certs:
    external: true
