services:
  nginx:
    image: nginxinc/nginx-unprivileged
    container_name: nginx-server
    restart: unless-stopped
    ports:
      - "80:8080"
      #- "443:443"
    volumes:
      # The vhost and conf volumes are only required
      # if you plan to obtain standalone certificates
      # - vhost:/etc/nginx/vhost.d
      # - conf:/etc/nginx/conf.d
      - ./config:/etc/nginx/conf.d
      - certs:/etc/nginx/certs:ro
    networks:
      - nginx_ip4_network
  dockergen:
    image: nginxproxy/docker-gen
    container_name: nginx-config
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl
      /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
  acme:
    image: nginxproxy/acme-companion:2.5.0
    container_name: nginx-certs
    restart: unless-stopped
    volumes_from:
      - nginx
    volumes:
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme:/etc/acme.sh
    environment:
      DEFAULT_EMAIL: noreply@${DOMAIN}
      ACME_CHALLENGE: DNS-01
      ACMESH_DNS_API_CONFIG: |-
        DNS_API: dns_ionos
        IONOS_PREFIX: ${PREFIX}
        IONOS_SECRET: ${SECRET}

networks:
  nginx_ip4_network:
    name: nginx_ip4_network

volumes:
  certs:
    external: true
