- name: Create Adguard app container directory
  ansible.builtin.file:
    path: "{{ quadlet_path }}/adguard"

- name: Create Adguard storage conf directory
  ansible.builtin.file:
    path: "{{ storage }}/adguard/conf"

- name: Create Adguard storage work directory
  ansible.builtin.file:
    path: "{{ storage }}/adguard/work"
