version: "3"
silent: true

vars:
  ENV_FILE: /etc/selfhosted.env
  HELP_MSG: "(in root directory use -- APP_NAME)"

tasks:
  start:
    dir: "{{.CLI_ARGS | default .USER_WORKING_DIR}}"
    desc: "Creates the specified container \t {{.HELP_MSG}}"
    cmd: sudo docker compose --env-file {{.ENV_FILE}} up -d
  update:
    dir: "{{.CLI_ARGS | default .USER_WORKING_DIR}}"
    desc: "Updates the specified container \t {{.HELP_MSG}}"
    cmd: sudo docker compose --env-file {{.ENV_FILE}} update
  stop:
    dir: "{{.CLI_ARGS | default .USER_WORKING_DIR}}"
    desc: "Removes the specified container \t {{.HELP_MSG}}"
    cmd: sudo docker compose --env-file {{.ENV_FILE}} down
  config:
    dir: "{{.CLI_ARGS | default .USER_WORKING_DIR}}"
    desc: "Outputs the specified container config \t {{.HELP_MSG}}"
    cmd: sudo docker compose --env-file {{.ENV_FILE}} config
  clean:
    desc: "Cleans up all unused docker resources"
    cmd: sudo docker system prune -a
