services:
  caddy:
    image: glopix/caddy-ionos-dns
    container_name: caddy
    restart: unless-stopped
    networks:
      - caddy_network
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAIN: ${DOMAIN:?error}
      IONOS_PREFIX: ${IONOS_PREFIX:?error}
      IONOS_SECRET: ${IONOS_SECRET:?error}
      MY_FRITZ_URL: ${MY_FRITZ_URL:?error}
    volumes:
      - ./data:/data
      - ./caddyfile:/etc/caddy/Caddyfile:ro
      - ./config:/config

networks:
  caddy_network:
    external: true

volumes:
  certs:
    external: true
