- name: Create {{ container_name }} domain secret
  containers.podman.podman_secret:
    data: "{{ domain }}"
    name: DOMAIN

- name: Create {{ container_name }} Ionos prefix secret
  containers.podman.podman_secret:
    data: "{{ ionos_prefix }}"
    name: IONOS_PREFIX

- name: Create {{ container_name }} Ionos secret secret
  containers.podman.podman_secret:
    data: "{{ ionos_secret }}"
    name: IONOS_SECRET
