theme: auto

server:
  address: "tcp://:9091/"
  disable_healthcheck: false
  endpoints:
    authz:
      forward-auth:
        implementation: "ForwardAuth"
        authn_strategies:
          - name: 'HeaderAuthorization'
            schemes:
              - 'Basic'
          - name: 'CookieSession'
    enable_pprof: false
    enable_expvars: false

totp:
  issuer: '{{env "DOMAIN"}}'
  period: 30
  skew: 1

authentication_backend:
  refresh_interval: always
  password_reset:
    disable: false
  file:
    path: '/config/users.yml'
    watch: true
    search:
      email: true
      case_insensitive: true
    password:
      algorithm: 'argon2'
      argon2:
        variant: 'argon2id'
        iterations: 3
        memory: 65536
        parallelism: 4
        key_length: 32
        salt_length: 16

identity_validation:
  reset_password:
    jwt_secret: '{{env "JWT_SECRET"}}'
    jwt_lifespan: "5 minutes"
    jwt_algorithm: "HS256"

access_control:
  default_policy: deny
  rules:
    - domain: '{{env "DOMAIN"}}'
      policy: bypass
    - domain: 'dns.{{env "DOMAIN"}}' # Adguard
      subject: "group:admin"
      policy: one_factor
    - domain: 'files.{{env "DOMAIN"}}' # FileBrowser
      subject: "group:admin"
      policy: one_factor
    - domain: 'home.{{env "DOMAIN"}}' # HomeAssistant
      subject: "group:admin"
      policy: one_factor
    - domain: 'music.{{env "DOMAIN"}}' # Navidrome
      policy: one_factor
    - domain: 'dancing.{{env "DOMAIN"}}' # Outline
      policy: one_factor
    - domain: 'cloud.{{env "DOMAIN"}}' # WebDav Cloud
      policy: one_factor

session:
  name: authelia_session
  secret: '{{env "SESSION_SECRET"}}'
  expiration: 1h
  inactivity: 5m
  cookies:
    - domain: '{{env "DOMAIN"}}'
      authelia_url: 'https://auth.{{env "DOMAIN"}}'

regulation:
  max_retries: 3
  find_time: 10m
  ban_time: 12h

storage:
  encryption_key: '{{env "STORAGE_ENCRYPTION_KEY"}}'
  local:
    path: /config/db.sqlite3

identity_providers:
  oidc:
    hmac_secret: '{{env "OIDC_HMAC_SECRET"}}'
    jwks:
      - key: |
          {{ fileContent "/secrets/OIDC_PRIVATE_KEY" | nindent 10 }}
    claims_policies:
      email:
        id_token: [ 'email', 'email_verified' ]
    clients:
      - client_id: OpenCloudWeb
        client_name: OpenCloud Web
        authorization_policy: one_factor
        require_pkce: false
        public: true
        redirect_uris:
          - https://cloud.{{env "DOMAIN"}}
          - https://cloud.{{env "DOMAIN"}}/oidc-callback.html
          - https://cloud.{{env "DOMAIN"}}/oidc-silent-redirect.html
        scopes:
          - openid
          - offline_access
          - profile
          - email
        response_types:
          - 'code'
      - client_id: OpenCloudAndroid
        client_name: OpenCloud Android
        authorization_policy: one_factor
        require_pkce: false
        public: true
        redirect_uris:
          - oc://android.opencloud.eu
        scopes:
          - openid
          - offline_access
          - profile
          - email
        response_types:
          - 'code'
      - client_id: outline
        client_name: Outline
        client_secret: '{{ env "CLIENT_SECRET"}}'
        authorization_policy: one_factor
        require_pkce: false
        public: false
        redirect_uris:
          - https://dancing.{{env "DOMAIN"}}/auth/oidc.callback
        scopes:
          - openid
          - offline_access
          - profile
          - email
        response_types:
          - 'code'
        grant_types:
          - 'authorization_code'
          - 'refresh_token'
        userinfo_signed_response_alg: "none"
        token_endpoint_auth_method: "client_secret_post"
        access_token_signed_response_alg: 'none'
      - client_id: bewcloud
        client_name: BewCloud
        client_secret: '{{ env "CLIENT_SECRET"}}'
        authorization_policy: one_factor
        pkce_challenge_method: 'S256'
        consent_mode: 'implicit'
        claims_policy: 'email'
        require_pkce: true
        public: false
        redirect_uris:
          - https://cloud.{{env "DOMAIN"}}/oidc/callback
        scopes:
          - openid
          - email
        userinfo_signed_response_alg: "none"
        token_endpoint_auth_method: "client_secret_post"
      - client_id: nextcloud
        client_name: Nextcloud
        client_secret: '{{ env "CLIENT_SECRET"}}'
        authorization_policy: one_factor
        pkce_challenge_method: 'S256'
        consent_mode: 'implicit'
        require_pkce: true
        public: false
        redirect_uris:
          - https://cloud.{{env "DOMAIN"}}/apps/user_oidc/code
        scopes:
          - openid
          - profile
          - groups
          - email
        response_types:
          - code
        grant_types:
          - 'authorization_code'
        userinfo_signed_response_alg: "none"
        access_token_signed_response_alg: 'none'
        token_endpoint_auth_method: "client_secret_post"
      - client_id: rustical
        client_secret: '{{ env "CLIENT_SECRET"}}'
        consent_mode: implicit
        public: false
        redirect_uris:
          - https://rustical.{{env "DOMAIN"}}/frontend/login/oidc/callback
        scopes:
          - openid
          - profile
          - groups
        token_endpoint_auth_method: client_secret_basic
      - client_id: budget
        client_name: ActualBudget
        client_secret: '{{ env "CLIENT_SECRET"}}'
        authorization_policy: one_factor
        redirect_uris:
          - https://budget.{{env "DOMAIN"}}/openid/callback
        scopes:
          - openid
          - groups
          - profile
          - email
        userinfo_signed_response_alg: "none"
        token_endpoint_auth_method: "client_secret_basic"
      - client_id: split
        client_name: SplitPro
        client_secret: '{{ env "CLIENT_SECRET"}}'
        authorization_policy: one_factor
        redirect_uris:
          - https://split.{{env "DOMAIN"}}/api/auth/callback/oidc
        scopes:
          - openid
          - offline_access
          - profile
          - email
        userinfo_signed_response_alg: "none"
        token_endpoint_auth_method: "client_secret_post"
      - client_id: fitness
        client_name: 'Sparky Fitness'
        client_secret: '{{ env "CLIENT_SECRET"}}'
        authorization_policy: one_factor
        pkce_challenge_method: 'S256'
        require_pkce: true
        public: false
        redirect_uris:
          - 'https://fitness.{{env "DOMAIN"}}/identity/connect/oidc-signin'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
        response_types:
          - 'code'
        grant_types:
          - 'authorization_code'
          - 'refresh_token'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_basic'
        access_token_signed_response_alg: 'none'
      - client_id: securo
        client_name: Securo
        client_secret: '{{ env "CLIENT_SECRET"}}'
        authorization_policy: one_factor
        pkce_challenge_method: 'S256'
        require_pkce: true
        public: false
        redirect_uris:
          - https://money.{{env "DOMAIN"}}/api/auth/oidc/callback
        scopes:
          - openid
          - profile
          - groups
          - email
      - client_id: oxicloud
        client_name: OxiCloud
        client_secret: '{{ env "CLIENT_SECRET"}}'
        authorization_policy: one_factor
        pkce_challenge_method: 'S256'
        require_pkce: true
        public: false
        redirect_uris:
          - https://files.{{env "DOMAIN"}}/api/auth/oidc/callback
        scopes:
          - openid
          - profile
          - groups
          - email
      - client_id: vaultwarden
        client_name: Vaultwarden
        client_secret: '{{ env "CLIENT_SECRET"}}'
        authorization_policy: one_factor
        pkce_challenge_method: 'S256'
        require_pkce: true
        public: false
        redirect_uris:
          - 'https://passwords.{{env "DOMAIN"}}/identity/connect/oidc-signin'
        scopes:
          - 'openid'
          - 'offline_access'
          - 'profile'
          - 'email'
        response_types:
          - 'code'
        grant_types:
          - 'authorization_code'
          - 'refresh_token'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_basic'
        access_token_signed_response_alg: 'none'

notifier:
  disable_startup_check: true
  smtp:
    username: '{{env "SMTP_USERNAME"}}'
    password: '{{env "SMTP_PASSWORD"}}'
    address: 'submissions://{{env "SMTP_HOST"}}:{{env "SMTP_PORT"}}'
    sender: 'Authelia <noreply@{{env "DOMAIN"}}>'
    subject: "{title}"
    disable_require_tls: false
    disable_starttls: false
