services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    restart: unless-stopped
    userns_mode: host
    #networks:
    #  - caddy_network
    environment:
      PUID: 1000
      PGID: 1000
      X_AUTHELIA_CONFIG_FILTERS: template
      JWT_SECRET: ${AUTHELIA_JWT_SECRET:?error}
      SESSION_SECRET: ${AUTHELIA_SESSION_SECRET:?error}
      OIDC_HMAC_SECRET: ${AUTHELIA_OIDC_HMAC_SECRET:?error}
      STORAGE_ENCRYPTION_KEY: ${AUTHELIA_STORAGE_ENCRYPTION_KEY:?error}
      OUTLINE_CLIENT_SECRET: ${OUTLINE_CLIENT_SECRET:?error}
      LDAP_USERNAME: ${LDAP_USERNAME:?error}
      LDAP_PASSWORD: ${LDAP_PASSWORD:?error}
      DOMAIN: ${DOMAIN:?error}
    volumes:
      - ./config:/config
      - ./secrets:/secrets
  ldap:
    image: lldap/lldap
    restart: unless-stopped
    container_name: ldap
    userns_mode: host
    #networks:
    #  - caddy_network
    environment:
      LLDAP_LDAP_BASE_DN: dc=example,dc=com
      LLDAP_KEY_SEED: ${LDAP_KEY_SEED:?error}
      LLDAP_JWT_SECRET: ${LDAP_JWT_KEY:?error}
      LLDAP_SMTP_OPTIONS__USER: ${SMTP_USERNAME:?error}
      LLDAP_SMTP_OPTIONS__PASSWORD: ${SMTP_PASSWORD:?error}
      LLDAP_SMTP_OPTIONS__SERVER: ${SMTP_HOST:?error}
      LLDAP_SMTP_OPTIONS__PORT: ${SMTP_PORT:?error}
      LLDAP_LDAP_USER_PASS: ${LDAP_PASSWORD:?error}
      LLDAP_LDAP_USER_DN: ${LDAP_USERNAME:?error}
      LLDAP_LDAP_USER_EMAIL: ${MAIL:?error}
    volumes:
      - "./ldap:/data"
#networks:
#  caddy_network:
#    external: true
