theme: auto

server:
  address: "tcp://:9091/"
  disable_healthcheck: false
  endpoints:
    enable_pprof: false
    enable_expvars: false
  #tls:
  #  certificate: ""
  #  key: ""

totp:
  issuer: '{{env "DOMAIN"}}'
  period: 30
  skew: 1

authentication_backend:
  refresh_interval: always
  password_reset:
    disable: false
  ldap:
    implementation: custom
    address: ldap://ldap:3890
    timeout: 5s
    start_tls: false
    base_dn: "dc=example,dc=com"
    users_filter: "(&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))"
    additional_users_dn: ou=people
    additional_groups_dn: ou=groups
    groups_filter: "(member={dn})"
    attributes:
      display_name: displayName
      username: uid
      group_name: cn
      mail: mail
    user: 'uid={{env "LDAP_USERNAME"}},ou=people,dc=example,dc=com'
    password: '{{env "LDAP_PASSWORD"}}'

identity_validation:
  reset_password:
    jwt_secret: '{{env "JWT_SECRET"}}'
    jwt_lifespan: "5 minutes"
    jwt_algorithm: "HS256"

access_control:
  default_policy: deny
  rules:
    - domain: '{{env "DOMAIN"}}'
      policy: bypass
    - domain: 'dns.{{env "DOMAIN"}}' # Adguard Home
      policy: one_factor
    - domain: 'dancing.{{env "DOMAIN"}}' # Outline Wiki
      policy: one_factor

session:
  name: authelia_session
  secret: '{{env "SESSION_SECRET"}}'
  expiration: 1h
  inactivity: 5m
  cookies:
    - domain: '{{env "DOMAIN"}}'
      authelia_url: 'https://auth.{{env "DOMAIN"}}'
      default_redirection_url: 'https://{{env "DOMAIN"}}'

regulation:
  max_retries: 3
  find_time: 10m
  ban_time: 12h

storage:
  encryption_key: '{{env "STORAGE_ENCRYPTION_KEY"}}'
  local:
    path: /config/db.sqlite3

identity_providers:
  oidc:
    hmac_secret: '{{env "OIDC_HMAC_SECRET"}}'
    jwks:
      - key: |
          {{ fileContent "/secrets/test_key.pem" | nindent 10 }}
    clients:
      - client_id: outline
        client_name: Outline
        client_secret: '{{ env "OUTLINE_CLIENT_SECRET"}}'
        authorization_policy: one_factor
        redirect_uris:
          - https://dancing.{{env "DOMAIN"}}/auth/oidc.callback
        scopes:
          - openid
          #- offline_access
          - profile
          - email

notifier:
  disable_startup_check: true
  smtp:
    address: 'smtp://{{env "SMTP_HOST"}}:{{env "SMTP_PORT"}}'
    username: '{{env "SMTP_USERNAME"}}'
    password: '{{env "SMTP_PASSWORD"}}'
    sender: 'Authelia <norepl@{{env "DOMAIN"}}>'
    identifier: localhost
    subject: "[Authelia] {title}"
    disable_require_tls: false
    disable_html_emails: false
    tls:
      skip_verify: false
      minimum_version: TLS1.2
