theme: auto

default_redirection_url: https://google.com/

server:
  host: 0.0.0.0
  port: 9091
  path: ""
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  tls:
    certificate: ""
    key: ""

totp:
  issuer: ${DOMAIN}
  period: 30
  skew: 1

authentication_backend:
  refresh_interval: always
  password_reset:
    disable: false
  ldap:
    implementation: custom
    address: ldap://ldap:3890
    timeout: 5s
    start_tls: false
    base_dn: dc=${DOMAIN},dc=de
    users_filter: "(&({mail_attribute}={input})(objectClass=person))"
    additional_users_dn: ou=people
    additional_groups_dn: ou=groups
    groups_filter: "(member={dn})"
    attributes:
      display_name: displayName
      username: uid
      group_name: cn
      mail: mail
      # distinguished_name: distinguishedName
      # member_of: memberOf
    user: uid=${USERNAME},ou=people,dc=example,dc=com
    password: ${PASSWORD}

access_control:
  default_policy: deny
  rules:
    - domain: "${DOMAIN}"
      policy: bypass
    - domain: "dns.${DOMAIN}" # Adguard Home
      policy: one_factor
    - domain: "dancing.${DOMAIN}" # Outline Wiki
      policy: one_factor
    - domain: "streaming.${DOMAIN}" # Jellyfin server
      policy: one_factor
    - domain: "home.${DOMAIN}" # Home Assistant
      policy: one_factor
    - domain: "pay.${DOMAIN}" # Spliit
      policy: one_factor

session:
  name: authelia_session
  domain: ${DOMAIN}
  expiration: 1h
  inactivity: 5m

regulation:
  max_retries: 3
  find_time: 10m
  ban_time: 12h

storage:
  local:
    path: /config/db.sqlite3

identity_providers:
  oidc:
    clients:
    - id: outline
      description: Outline
      secret: '$pbkdf2-sha512$310000$c8p78n7pUMln0jzvd4aK4Q$JNRBzwAo0ek5qKn50cFzzvE9RXV88h1wJn5KGiHrD0YKtZaR/nCb2CJPOsKaPK0hjf.9yHxzQGZziziccp6Yng'
      public: false
      userinfo_signing_algorithm: none
      authorization_policy: one_factor
      redirect_uris:
        - https://dancing.${DOMAIN}/auth/oidc.callback
      scopes:
        - openid
        - offline_access
        - profile
        - email

notifier:
  disable_startup_check: true #true/false
  smtp:
    username: youremail@gmail.com #your email address
    password: Y0uRp@55W0rD! #your email password
    host: smtp.gmail.com #email smtp server
    port: 587 #email smtp port
    sender: youremail@gmail.com
    identifier: localhost
    subject: "[Authelia] {title}" #email subject
    startup_check_address: youremail@gmail.com
    disable_require_tls: false
    disable_html_emails: false
    tls:
      skip_verify: false
      minimum_version: TLS1.2
