services:
  authelia:
    image: authelia/authelia:4.37.5
    container_name: authelia
    restart: unless-stopped
    networks:
      - nginx_ip4_network
    environment:
      AUTHELIA_JWT_SECRET_FILE: /secrets/JWT_SECRET
      AUTHELIA_SESSION_SECRET_FILE: /secrets/SESSION_SECRET
      AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY_FILE: /secrets/OIDC_PRIVATE_KEY
      AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE: /secrets/OIDC_HMAC_SECRET
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /secrets/STORAGE_ENCRYPTION_KEY
      VIRTUAL_HOST: auth.${DOMAIN}
      VIRTUAL_PORT: 9091
    volumes:
      - ./config:/config
      - ./secrets:/secrets
  ldap:
    image: lldap/lldap:stable
    restart: unless-stopped
    container_name: ldap
    networks:
      - nginx_ip4_network
    environment:
      VIRTUAL_HOST: user.${DOMAIN}
      VIRTUAL_PORT: 17170
    volumes:
      - "./ldap:/data"

networks:
  nginx_ip4_network:
    external: true
