services:
  authelia:
    image: authelia/authelia:4.38.15
    container_name: authelia
    restart: unless-stopped
    user: 3000:3000
    networks:
      - nginx_ip4_network
    environment:
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: /secrets/JWT_SECRET
      AUTHELIA_SESSION_SECRET_FILE: /secrets/SESSION_SECRET
      AUTHELIA_IDENTITY_PROVIDERS_OIDC_JWKS_KEY_FILE: /secrets/OIDC_PRIVATE_KEY
      AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE: /secrets/OIDC_HMAC_SECRET
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /secrets/STORAGE_ENCRYPTION_KEY
      LETSENCRYPT_HOST: "*.${DOMAIN},${DOMAIN}"
      VIRTUAL_HOST: auth.${DOMAIN}
      VIRTUAL_PORT: 9091
    volumes:
      - ./config:/config
      - ./secrets:/secrets
  ldap:
    image: lldap/lldap:latest-alpine-rootless
    restart: unless-stopped
    container_name: ldap
    user: 3000:3000
    networks:
      - nginx_ip4_network
    environment:
      VIRTUAL_HOST: user.${DOMAIN}
      LETSENCRYPT_HOST: "*.${DOMAIN},${DOMAIN}"
      VIRTUAL_PORT: 17170
    volumes:
      - "./ldap:/data"

networks:
  nginx_ip4_network:
    external: true
