jwt_secret = "${JWT_SECRET}"
key_seed = "${KEY_SEED}"

ldap_base_dn = "dc=${DOMAIN},dc=de"

ldap_user_dn = "${USERNAME}"
ldap_user_pass = "${PASSWORD}"
ldap_user_email = "${EMAIL}"

database_url = "sqlite:///data/users.db?mode=rwc"

[smtp_options]
#enable_password_reset=true

server = ${SMTP_SERVER}
port = ${SMTP_PORT}
smtp_encryption = "TLS"
# NONE, TLS, STARTTLS

user = ${SMTP_USERNAME}
password = ${SMTP_PASSWORD}

from = "Password reset requested <noreply@${DOMAIN}>"
reply_to = "Do not reply <noreply@${DOMAIN}>"
