services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: home-server
    restart: unless-stopped
    networks:
      - caddy_network
    volumes:
      - ./home:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
  matter-server:
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    container_name: home-matter
    restart: unless-stopped
    networks:
      - caddy_network
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./matter/data:/data/
      - /run/dbus:/run/dbus:ro

networks:
  caddy_network:
    external: true
