services:
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    container_name: homeassistant
    restart: unless-stopped
    network_mode: host
    privileged: true
    ports:
      - "80:8123"
    volumes:
      - /PATH_TO_YOUR_CONFIG:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    environment:
      VIRTUAL_HOST: "home.${DOMAIN}"
      LETSENCRYPT_HOST: "*.${DOMAIN},${DOMAIN}"
      VIRTUAL_PORT: 8123

networks:
  nginx_ip4_network:
    external: true
