- name: Create Jellyfin app container directory
  ansible.builtin.file:
    path: "{{ quadlet_path }}/jellyfin"

- name: Create Jellyfin cache directory
  ansible.builtin.file:
    path: "{{ storage }}/fellyfin/cache"

- name: Create Jellyfin config directory
  ansible.builtin.file:
    path: "{{ storage }}/fellyfin/config"
