- name: Set unprivileged port binding to 53
  ansible.builtin.copy:
    src: 10-unprivileged-port.conf
    dest: /etc/sysctl.d
  become: true

- name: Enable linger to start container without login
  ansible.builtin.file:
    path: "/var/lib/systemd/linger/{{ ansible_user_id }}"
    state: touch
  become: true
