- name: Copy {{ container_name }} container files
  import_tasks: container.yml

- name: Create {{ container_name }} volumes
  import_tasks: volumes.yml

- name: Create {{ container_name }} secrets
  import_tasks: secrets.yml
