- name: Fixing {{ container_name }} DB connection settings
  ansible.builtin.set_fact:
    db_username_fixed: "{{ db_username }}"
    db_password_fixed: "{{ db_password }}"

- name: Create {{ container_name }} secret
  containers.podman.podman_secret:
    data: "{{ secret }}"
    name: SPLIT_SECRET

- name: Create {{ container_name }} DB username
  containers.podman.podman_secret:
    data: "{{ db_username_fixed }}"
    name: SPLIT_DB_USERNAME

- name: Create {{ container_name }} DB password
  containers.podman.podman_secret:
    data: "{{ db_password_fixed }}"
    name: SPLIT_DB_PASSWORD

- name: Create {{ container_name }} database URL
  containers.podman.podman_secret:
    data: "{{ db_url }}"
    name: SPLIT_DB_URL
