---
title: HomeLab

color: slate
theme: dark

useEqualHeights: true
disableCollapse: true

disableUpdateCheck: true

headerStyle: clean
hideVersion: true

layout:
  Applications:
    style: row
    header: false
    columns: 3
  System management:
    style: row
    header: true
    columns: 3
