services:
  diun:
    image: crazymax/diun
    container_name: imgage-observer
    restart: unless-stopped
    command: serve
    networks:
      - caddy_network
    environment:
      TZ: Europe/Berlin
      DIUN_NOTIF_MAIL_HOST: ${SMTP_HOST:?error}
      DIUN_NOTIF_MAIL_USERNAME: ${SMTP_USERNAME:?error}
      DIUN_NOTIF_MAIL_PASSWORD: ${SMTP_PASSWORD:?error}
      DIUN_NOTIF_MAIL_FROM: noreply@${DOMAIN:?error}
      DIUN_NOTIF_MAIL_PORT: ${SMTP_PORT:?error}
      DIUN_NOTIF_MAIL_TO: ${EMAIL:?error}
    volumes:
      - "./config.yml:/diun.yml:ro"
      - "./observe.yml:/observe.yml:ro"
      - "./data:/data"

networks:
  caddy_network:
    external: true
