- name: Create LDAP JWT key
  containers.podman.podman_secret:
    name: LDAP_JWT_KEY
    data: query('community.general.random_string', override_all=hex_chars, length=128)

- name: Create LDAP key seed
  containers.podman.podman_secret:
    name: LDAP_KEY_SEED
    data: query('community.general.random_string', override_all=hex_chars, length=128)

- name: Create LDAP super admin username
  containers.podman.podman_secret:
    name: LDAP_USERNAME
    data: query('community.general.random_string', length=24)

- name: Create LDAP super admin password
  containers.podman.podman_secret:
    name: LDAP_PASSWORD
    data: query('community.general.random_string', base64=True, length=48)
