- name: Create {{ container_name }} JWT key
  containers.podman.podman_secret:
    data: "{{ jwt_key }}"
    name: LDAP_JWT_KEY

- name: Create {{ container_name }} key seed
  containers.podman.podman_secret:
    data: "{{ key_seed }}"
    name: LDAP_KEY_SEED

- name: Create {{ container_name }} super admin username
  containers.podman.podman_secret:
    data: "{{ username }}"
    name: LDAP_USERNAME

- name: Create {{ container_name }} super admin password
  containers.podman.podman_secret:
    data: "{{ password }}"
    name: LDAP_PASSWORD
