[Service]
Restart=no
TimeoutStartSec=900
RestartSec=10

EnvironmentFile=%h/.config/containers/systemd/shared.env
WorkingDirectory=%h/.config/containers/systemd

[Container]
NoNewPrivileges=true

UserNS=keep-id:uid=65534,gid=65534
User=65534:65534
#ReadOnly=true

[Install]
WantedBy=default.target
