[Service]
Restart=no
RestartSec=10

TimeoutStartSec=900

[Container]
AutoUpdate=registry
UserNS=keep-id:uid=65534,gid=65534
NoNewPrivileges=true

Network=caddy.network

[Install]
WantedBy=default.target