[Service]
Restart=no
TimeoutStartSec=900
RestartSec=10

WorkingDirectory=/etc/containers/systemd

Environment=VOLUMES_DIR=/etc/containers/volumes
Environment=MEDIA_DIR=/etc/containers/media

Environment=DOMAIN=
Environment=IP_ADDRESS=

[Container]
#NoNewPrivileges=true

UserNS=auto
#ReadOnly=true
Pull=newer

[Install]
WantedBy=default.target
