- name: "Create {{ container_name }} volume base directory"
  ansible.builtin.file:
    path: "{{ volumes }}/{{ container_name }}"
    state: directory
    recurse: true

- name: "Create {{ container_name }} volume directories"
  ansible.builtin.file:
    path: "{{ volumes }}/{{ container_name }}/{{ item.path }}"
    state: directory
    recurse: true
  with_filetree: "templates/volumes/"
  when: item.state == 'directory'

- name: "Copy {{ container_name }} configuration file"
  ansible.builtin.copy:
    dest: "{{ volumes }}/{{ container_name }}/config"
    src: configuration.yml
