services:
  otbr:
    image: siliconlabsinc/openthread-border-router:gsdk-4.4.0
    command: --radio-url spinel+hdlc+uart:///dev/ttyUSB0?uart-baudrate=460800 --backbone-interface eth0
    container_name: home-thread
    restart: unless-stopped
    privileged: true
    networks:
      home_network:
        ipv4_address: 192.168.178.200
    environment:
      NETWORK_ACCESS: internal
      VIRTUAL_HOST: "thread.${DOMAIN}"
      VIRTUAL_PORT: 80
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.forwarding=1
      - net.ipv6.conf.all.forwarding=1
    ports:
      - 8080:80
      - 8081:8081
    dns:
      - 127.0.0.1
    volumes:
      - /dev/ttyUSB0:/dev/ttyUSB0

networks:
  home_network:
    enable_ipv6: true
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: "192.168.178.0/24"
          gateway: "192.168.178.1"
        - subnet: "fd00:4a82:739b::/64"
          gateway: "fd00:4a82:739b::ca0e:14ff:fe8d:8d84"
