- name: Create Immich container directory
  ansible.builtin.file:
    path: "{{ quadlet_path }}/immich"
    state: directory
    recurse: true

- name: "Copy Immich container files"
  ansible.builtin.template:
    dest: "{{ quadlet_path }}/immich/{{ item.path }}"
    src: "{{ item.src }}"
  with_filetree: "templates/container/"
  when: item.state == 'file'
