db:
  path: diun.db

watch:
  workers: 10
  schedule: "0 0 * * *"
  firstCheckNotif: true
  runOnStartup: true
  jitter: 30m

notif:
  mail:
    host: ${SMTP_SERVER}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    from: noreply@${DOMAIN}
    to:
      - ${EMAIL}

regopts:
  - name: crazymax/diun
  - name: adguard/adguardhome
  - name: outlinewiki/outline

providers:
  file:
    directory: ./observe.yml
