services:
  diun:
    image: crazymax/diun:latest
    container_name: imgage-observer
    restart: unless-stopped
    command: serve
    networks:
      - nginx_ip4_network
    environment:
      - "TZ=Europe/Berlin"
    volumes:
      - "./config.yml:/diun.yml:ro"
      - "./observe.yml:/observe.yml:ro"
      - "./data:/data"

networks:
  nginx_ip4_network:
    external: true
