services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    networks:
      - caddy_network
    volumes:
      - ./cache:/cache
      - ./config:/config
      - /media:/media:ro

networks:
  caddy_network:
    external: true
