[network]
stack_fqdn = "api-roborock.${DOMAIN}"
listener_mode = "external_tls"
bind_host = "0.0.0.0"
# Backend listener ports.
mqtt_tls_port = 8881
https_port = 5555
# Public ports advertised to clients.
advertised_mqtt_tls_port = 8883
advertised_https_port = 443

region = "us"

[broker]
mode = "embedded"
mosquitto_binary = "mosquitto"
enable_topic_bridge = true
host = "127.0.0.1"
port = 18830

[storage]
data_dir = "/data"

[tls]
mode = "provided"

[admin]
password_hash = "abc"
session_secret = "123123123123123123123123"

protocol_login_email = "noreply@${DOMAIN}"
protocol_login_pin_hash = "sdfhk"
