- name: Setup Homelab
  hosts: raspberry

  module_defaults:
    containers.podman.podman_secret:
      skip_existing: true

  vars_prompt:
    - name: domain
      prompt: Enter domain
      private: false
    #  - name: email
    #    prompt: Enter private E-Mail
    #    private: false
    - name: ionos_prefix
      prompt: Enter Ionos API prefix
      private: false
    - name: ionos_secret
      prompt: Enter Ionos API secret
      private: false
  #  - name: smtp_host
  #    prompt: Enter SMTP host
  #    private: false
  #  - name: smtp_port
  #    prompt: Enter SMTP port
  #    private: false
  #  - name: smtp_username
  #    prompt: Enter SMTP username
  #    private: false
  #  - name: smtp_password
  #    prompt: Enter SMTP password
  #    private: true
  #    unsafe: true

  vars:
    hex_chars: 0123456789abcdef
    user_ns: keep-id:uid=65534,gid=65534

    container_start_timeout: 900

    quadlet_path: "{{ ansible_facts['env']['HOME'] }}/.config/containers/systemd"
    #quadlet_path: "{{  ansible_facts['env']['HOME'] }}/containers/systemd"

    volumes: "{{  ansible_facts['env']['HOME'] }}/storage/volumes"
    media: "{{  ansible_facts['env']['HOME'] }}/storage/media"

  roles:
    - systemd
    # Setup containers
    - adguard
    - authelia
    - budget
    - caddy
    - filebrowser
    - homeassistant
    - homepage
    #- immich
    - jellyfin
    - ldap
    - outline
    - splitpro
    - vaultwarden

  post_tasks:
    - name: Reboot machine to apply changes
      ansible.builtin.reboot:
      become: true
