- name: Create Authelia JWT secret
  containers.podman.podman_secret:
    name: AUTHELIA_JWT_SECRET
    data: query('community.general.random_string', override_all=hex_chars, length=128)

- name: Create Authelia OIDC HMAC secret
  containers.podman.podman_secret:
    name: AUTHELIA_OIDC_HMAC_SECRET
    data: query('community.general.random_string', override_all=hex_chars, length=128)

- name: Create Authelia storage encryption key
  containers.podman.podman_secret:
    name: AUTHELIA_STORAGE_ENCRYPTION_KEY
    data: query('community.general.random_string', override_all=hex_chars, length=128)

- name: Create Authelia session secret
  containers.podman.podman_secret:
    name: AUTHELIA_SESSION_SECRET
    data: query('community.general.random_string', override_all=hex_chars, length=128)

- name: Generate an OpenSSH rsa keypair with a different size (2048 bits)
  community.crypto.openssh_keypair:
    path: "{{ storage }}/authelia/oidc_jwks_key"
    private_key_format: pkcs8
    backend: cryptography
    size: 2048
    type: rsa
