- name: Create {{ container_name }} JWT secret
  containers.podman.podman_secret:
    name: AUTHELIA_JWT_SECRET
    data: "{{ jwt_secret }}"

- name: Create {{ container_name }} OIDC HMAC secret
  containers.podman.podman_secret:
    name: AUTHELIA_OIDC_HMAC_SECRET
    data: "{{ oidc_hmac_secret }}"

- name: Create {{ container_name }} storage encryption key
  containers.podman.podman_secret:
    name: AUTHELIA_STORAGE_ENCRYPTION_KEY
    data: "{{ storage_enc_key }}"

- name: Create {{ container_name }} session secret
  containers.podman.podman_secret:
    name: AUTHELIA_SESSION_SECRET
    data: "{{ session_secret }}"

- name: Create {{ container_name }} oidc JWKS key
  community.crypto.openssh_keypair:
    path: "{{ volumes }}/{{ container_name }}/oidc_jwks_key"
    private_key_format: pkcs8
    backend: cryptography
    size: 2048
    type: rsa
