---
- Services:
    - Adguard Home:
        href: https://dns.{{ domain }}
        description: Networkwide Adblocker
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/adguard-home-light.svg
    - Actual Budget:
        href: https://budget.{{ domain }}
        description: Personal finance app
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/actual-budget-light.svg
    - File Browser:
        href: https://files.{{ domain }}
        description: Cloud & Web File Browser
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/file-browser-light.svg
    - Home Assistant:
        href: https://home.{{ domain }}
        description: Local and private Home automation
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/home-assistant-light.svg
    - Immich:
        href: https://photos.{{ domain }}
        description: Photo and video management
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/immich-light.svg
    - Jellyfin:
        href: https://streaming.{{ domain }}
        description: Media streaming system
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/jellyfin-light.svg
    - Outline:
        href: https://dancing.{{ domain }}
        description: Knowledge base for dance
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/outline-light.svg
    - SplitPro:
        href: https://split.{{ domain }}
        description: Splitwise alternative
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/budget-board-light.svg
    - Vaultwarden:
        href: https://passwords.{{ domain }}
        description: Password manager
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/vaultwarden-light.svg
