- name: Create {{ container_name }} container directory
  ansible.builtin.file:
    path: "{{ quadlet_path }}/{{ container_name }}"
    state: directory
    recurse: true

- name: "Copy {{ container_name }} container files"
  ansible.builtin.template:
    dest: "{{ quadlet_path }}/{{ container_name }}/{{ item.path }}"
    src: "{{ item.src }}"
  with_filetree: "templates/container/"
  when: item.state == 'file'
