- name: Create Caddy container directory
  ansible.builtin.file:
    path: "{{ quadlet_path }}/caddy"

- name: Create Caddy config directory
  ansible.builtin.file:
    path: "{{ storage }}/caddy"

- name: Create Caddy certs directory
  ansible.builtin.file:
    path: "{{ storage }}/caddy/certs"
