- name: Create Caddy domain secret
  containers.podman.podman_secret:
    data: "{{ domain }}"
    name: DOMAIN

- name: Create Caddy Ionos prefix secret
  containers.podman.podman_secret:
    data: "{{ ionos_prefix }}"
    name: IONOS_PREFIX

- name: Create Caddy Ionos secret secret
  containers.podman.podman_secret:
    data: "{{ ionos_secret }}"
    name: IONOS_SECRET
