services:
  adguard:
    image: adguard/adguardhome:v0.107.52
    container_name: adguard
    restart: unless-stopped
    networks:
      - nginx_ip4_network
    ports:
      - "853:853/tcp"
      - "853:853/udp"
      - "3000:3000"
    environment:
      VIRTUAL_HOST: "dns.${DOMAIN}"
      VIRTUAL_PORT: 80
    volumes:
      - certs:/opt/adguardhome/certs:ro
      - ./workdir:/opt/adguardhome/work
      - ./confdir:/opt/adguardhome/conf

networks:
  nginx_ip4_network:
    external: true

volumes:
  certs:
    external: true
