services:
  spliit-app:
    image: crazymax/spliit
    container_name: spliit-app
    restart: unless-stopped
    networks:
      - nginx_ip4_network
    environment:
      TZ: Europe/Berlin
      POSTGRES_HOST: spliit-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: spliit
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      VIRTUAL_HOST: "pay.${DOMAIN}"
      LETSENCRYPT_HOST: "*.${DOMAIN}"
      VIRTUAL_PORT: 3000
    depends_on:
      spliit-db:
        condition: service_healthy

  spliit-db:
    image: postgres:latest
    container_name: spliit-db
    restart: unless-stopped
    networks:
      - nginx_ip4_network
    #ports:
    #  - 5432:5432
    environment:
      TZ: Europe/Berlin
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: spliit
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  nginx_ip4_network:
    external: true
