- name: "Create {{ container_name }} volume base directory"
  ansible.builtin.file:
    path: "{{ volumes }}/{{ container_name }}"
    state: directory
    recurse: true

- name: "Create {{ container_name }} volume directories"
  ansible.builtin.file:
    path: "{{ volumes }}/{{ container_name }}/{{ item.path }}"
    state: directory
    recurse: true
  with_filetree: "templates/volumes/"
  when: item.state == 'directory'

- name: "Copy {{ container_name }} configuration files"
  ansible.builtin.template:
    dest: "{{ volumes }}/{{ container_name }}/{{ item.path }}"
    src: "{{ item.src }}"
  with_filetree: "templates/volumes/"
  when: item.state == 'file'

- name: "Copy {{ container_name }} BubbleCard file"
  ansible.builtin.copy:
    dest: "{{ volumes }}/{{ container_name }}/www"
    src: "{{ item }}"
  loop:
    - bubble-card.js
    - bubble-pop-up-fix.js
    - mini-graph-card-bundle.js
