- name: Create Actual Budget client secret
  containers.podman.podman_secret:
    name: ACTUAL_BUDGET_CLIENT_SECRET
    data: query('community.general.random_string', override_all=hex_chars, length=128)
